### ISSUE TITLE
Add support PNG to benefit from colors

### ISSUE THREAD

**Issue by ghilainm** [plantuml-stdlib/gilbarbara-plantuml-sprites#14]
Hello,

I think it would be nice to also support the PNG format in addition to the sprite format to benefit from colors. It could be done in the same fashion as https://github.com/awslabs/aws-icons-for-plantuml.

**Comment by ghilainm** [comment]
I think it is already supported somehow :). Maybe it would be nice to document it in the readme for future readers :).

Example:

component "<img:https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/pngs/github-octocat.png>\nGitHub" as github

**Comment by Potherca** [comment]
Hi @ghilainm, 

An example explaining how to use color has been added to the README.

Thank you for taking the time to report this!

Regards,
Ben.
